# Generated by Django 6.0.2 on 2026-02-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('ADOPTED', 'Adopted')], default='AVAILABLE', max_length=20),
        ),
    ]
